name: Build and Push Docker Image

on:
  push:

env:
  DOCKERHUB_USERNAME: zakiego
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: zakiego/ipuk
  IMAGE_TAG: dev
  COOLIFY_WEBHOOK_URL_PRIVATE: ${{ secrets.COOLIFY_WEBHOOK_URL_PRIVATE }}
  COOLIFY_WEBHOOK_URL_PUBLIC: ${{ secrets.COOLIFY_WEBHOOK_URL_PUBLIC }}
  COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  coolify:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Trigger Webhook (Private)
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_URL_PRIVATE }}' --header 'Authorization: Bearer ${{ env.COOLIFY_TOKEN }}'

      - name: Trigger Webhook (Public)
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_URL_PUBLIC }}' --header 'Authorization: Bearer ${{ env.COOLIFY_TOKEN }}'
